chore: Add more tracing
mamba-org/resolvo pull request #55
Opened 2024-07-17 14:39 UTC by jjerphan

2024-07-17 15:02 UTC, baszalmstra requested changes
Thanks for this! 

You changed a lot of places to display ids instead of the rhings the ids represent. I can understand that this makes debugging some things easier but it also makes following the general flow of the algorithm much harder. Could we maybe show both? The id and the representation of the id? 

You inplemented Display in a few places in a way that almost exactly mimics the (derived) Debug trait. Maybe you can use rhat instead?

I think the levels are sometimes quite high. Perhaps consider downgrading some info and debug logs to trace level instead?

2024-07-17 15:28 UTC, jjerphan commented on src/solver/cache.rs
> +                tracing::debug!(
Yes, let me change all the new `info` and `debug` to `trace`.

2024-07-17 15:33 UTC, jjerphan commented on src/solver/mod.rs
> +impl Display for AddClauseOutput {
I had to implement it, but I guess I should be able to change part of the implementation so that the `Debug` trait is used.

2024-07-18 14:28 UTC, baszalmstra commented on src/internal/id.rs
> +}
You can just use `InternalSolvableId::from(id)` instead!

2024-07-18 14:28 UTC, baszalmstra commented on src/solver/cache.rs
> +                );
`display_name` returns something that implements `Display`. You can then use `{}` to format it directly without having to convert to a string first:

```suggestion
                tracing::trace!(
                    "Getting matching candidates for package: {}",
                    self.provider.display_name(package_name_id)
                );
```

2024-07-18 14:28 UTC, baszalmstra commented on src/solver/mod.rs
> +            );
I ran a little test and this popped-up quite a lot, is this useful to see in the logs?

2024-07-18 14:28 UTC, baszalmstra commented on src/solver/mod.rs
> +        tracing::trace!("Propagate");
Is this useful? It always follows an "install". Perhaps add the level at least?

2024-07-18 14:28 UTC, baszalmstra commented on src/solver/mod.rs
> +            );
This is added very often to the logs because its visited on every propagation.

2024-07-18 14:28 UTC, baszalmstra commented on src/solver/mod.rs
> +            );
Same here. Only the one below seems interesting.

2024-07-18 15:16 UTC, baszalmstra approved these changes

2024-07-18 15:16 UTC, merged